import type { DefaultTheme } from "styled-components";

export const lightTheme: DefaultTheme = {
  background: "#ffffff",
  homeText: "#ffffffff",
  text: "#000000ff",
  buttonPrimary: "#ffffff",
  buttonThemePrimaryText: "#000000ff",
  buttonPrimaryText: "#ffffffff",
  homeButtonPrimaryText: "#000000ff",
  buttonOutlineHover: "rgba(0, 0, 0, 0.1)",
  backgroundImage: "url('fundo.svg')",
  buttonSecondary: "#999",
  buttonSecondaryText: "#fff",
  buttonPrimaryHover: "#0096c7",
  buttonSecondaryHover: "#777",
  textPrimary: "#222",
  textSecondary: "#333",
  inputBackground: "#fff",
  inputBorder: "#ccc",
  cardBackground: "#ffffff",
  examCardBackground: "#f0fcff",
  textPlaceholder: "#777",
  backgroundSecondary: "#ffffff",
  card: "#ffffff",
  border: "#e0e0e0",
  success: "#4caf50",
  error: "#f44336",
  primary: "#007bff" // azul claro
};

export const darkTheme: DefaultTheme = {
  background: "#121212",
  homeText: "#ffffffff",
  text: "#ffffff",
  textPrimary: "#ffffff",
  textSecondary: "#cccccc",
  buttonPrimary: "#1f1f1f",
  buttonThemePrimaryText: "#ffffffff",
  buttonPrimaryText: "#ffffff",
  homeButtonPrimaryText: "#ffffff",
  buttonOutlineHover: "rgba(255, 255, 255, 0.2)",
  backgroundImage: "none",
  buttonSecondary: "#444",
  buttonSecondaryText: "#fff",
  buttonSecondaryHover: "#555",
  buttonPrimaryHover: "#0096c7",
  inputBackground: "#2c2c2c",
  inputBorder: "#555",
  cardBackground: "#1e1e1e",
  examCardBackground: "#1e1e1e",
  textPlaceholder: "#aaaaaa",
  backgroundSecondary: "#1b1b1b",
  card: "#1e1e1e",
  border: "#333333",
  success: "#4caf50",
  error: "#f44336",
  primary: "#3399ff" // azul escuro

};
