import type { DefaultTheme } from 'styled-components'

export const lightTheme: DefaultTheme = {
  background: '#ffffff',
  secondaryBackground: '#f8f8f8',
  text: '#000000',
  buttonPrimary: '#ffffff',
  buttonPrimaryText: '#ffffff',
  buttonOutlineHover: 'rgba(0, 0, 0, 0.1)',
  backgroundImage: "url('fundo.svg')",
  primary: '#007bff',
  homeText: '#ffffff',
  buttonThemePrimaryText: '#000000',
  homeButtonPrimaryText: '#000000',
  buttonSecondary: '#e0e0e0',
  buttonSecondaryText: '#000000',
  buttonSecondaryHover: '#c0c0c0',
  secondary: '#e0e0e0',
  secondaryHover: '#c0c0c0',
  buttonPrimaryHover: '#0096c7',
  textPrimary: '#222',
  textSecondary: '#333',
  cardBackground: '#ffffff',
  examCardBackground: '#f0fcff',
  inputBackground: '#ffffff',
  inputBorder: '#ccc',
  backgroundSecondary: '#ffffff',
  card: '#ffffff',
  border: '#e0e0e0',
  success: '#4caf50',
  error: '#f44336',
  textPlaceholder: '#333'
}

export const darkTheme: DefaultTheme = {
  background: '#121212',
  secondaryBackground: '#1b1b1b',
  text: '#ffffff',
  buttonPrimary: '#3399ff',
  buttonPrimaryText: '#ffffff',
  buttonOutlineHover: 'rgba(255, 255, 255, 0.2)',
  backgroundImage: 'none',
  primary: '#3399ff',
  homeText: '#ffffff',
  buttonThemePrimaryText: '#ffffff',
  homeButtonPrimaryText: '#ffffff',
  buttonSecondary: '#444444',
  buttonSecondaryText: '#ffffff',
  buttonSecondaryHover: '#555555',
  secondary: '#444444',
  secondaryHover: '#555555',
  buttonPrimaryHover: '#0096c7',
  textPrimary: '#ffffff',
  textSecondary: '#cccccc',
  cardBackground: '#1e1e1e',
  examCardBackground: '#1e1e1e',
  inputBackground: '#2c2c2c',
  inputBorder: '#555',
  backgroundSecondary: '#1b1b1b',
  card: '#1e1e1e',
  border: '#333333',
  success: '#4caf50',
  error: '#f44336',
  textPlaceholder: '#aaaaaa'
}
